export type KodeAreaMap = Record<string, string[]>;

export const kodeArea: KodeAreaMap = {
  "021": [
    "Kepulauan Seribu",
    "Jakarta Barat",
    "Jakarta Pusat",
    "Jakarta Selatan",
    "Jakarta Timur",
    "Jakarta Utara",
    "Tigaraksa (Kabupaten Tangerang)",
    "Kota Tangerang",
    "Kota Tangerang Selatan (Pamulang)",
    "Kota Bekasi",
    "Kabupaten Bekasi",
    "Kota Depok kecuali Sawangan dan Bojongsari",
    "Cibinong - Cileungsi - Klapanunggal - Jonggol - Sukamakmur - Cariu - Tanjungsari (Kabupaten Bogor)",
  ],
  "022": [
    "Kota Bandung",
    "Kota Cimahi",
    "Soreang (Kabupaten Bandung)",
    "Lembang - Ngamprah (Kabupaten Bandung Barat)",
  ],
  "0231": ["Kota Cirebon", "Sumber - Losari (Kabupaten Cirebon)"],
  "0232": ["Kabupaten Kuningan"],
  "0233": ["Kabupaten Majalengka"],
  "0234": ["Kabupaten Indramayu"],
  "0251": [
    "Kota Bogor",
    "Sawangan - Bojongsari (Kota Depok)",
    "Kabupaten Bogor kecuali Cibinong, Cileungsi, Klapanunggal, Jonggol, Sukamakmur, Cariu, dan Tanjungsari",
  ],
  "0252": ["Rangkasbitung (Kabupaten Lebak)"],
  "0253": ["Pandeglang - Labuan (Kabupaten Pandeglang)"],
  "0254": ["Kota Serang", "Kabupaten Serang", "Merak (Kota Cilegon)"],
  "0257": ["Cinangka (Kabupaten Serang)"],
  "0260": ["Kabupaten Subang"],
  "0261": ["Kabupaten Sumedang"],
  "0262": ["Kabupaten Garut"],
  "0263": ["Kabupaten Cianjur"],
  "0264": ["Kabupaten Purwakarta", "Cikampek (Kabupaten Karawang)"],
  "0265": [
    "Kota Tasikmalaya",
    "Kadipaten - Singaparna (Kabupaten Tasikmalaya)",
    "Kota Banjar",
    "Kabupaten Ciamis",
    "Kabupaten Pangandaran",
  ],
  "0266": [
    "Kota Sukabumi",
    "Palabuhanratu (Kabupaten Sukabumi)",
    "Gekbrong (Kabupaten Cianjur)",
  ],
  "0267": ["Kabupaten Karawang"],
  "024": ["Semarang", "Ungaran", "Demak (Mranggen, Sayung)"],
  "0271": [
    "Surakarta (Solo)",
    "Kartasura",
    "Sukoharjo",
    "Karanganyar",
    "Sragen",
    "Sebagian Boyolali",
  ],
  "0272": ["Klaten"],
  "0273": ["Wonogiri", "Purwantoro", "Pracimantoro"],
  "0274": [
    "Prambanan",
    "Klaten (wilayah berbatasan Yogyakarta)",
    "Kota Yogyakarta",
    "Sleman",
    "Bantul",
    "Gunung Kidul",
    "Kulon Progo",
  ],
  "0275": ["Purworejo", "Kutoarjo"],
  "0276": ["Boyolali"],
  "0280": ["Majenang", "Sidareja (Kabupaten Cilacap bagian barat)"],
  "0281": ["Purwokerto", "Banyumas", "Sumpiuh", "Purbalingga"],
  "0282": ["Cilacap bagian timur", "Kebasen (wilayah berbatasan Cilacap)"],
  "0283": ["Tegal", "Slawi", "Brebes (kecuali Bumiayu)"],
  "0284": ["Pemalang", "Tegal bagian timur"],
  "0285": ["Pekalongan", "Batang bagian barat", "Comal"],
  "0286": ["Banjarnegara", "Wonosobo"],
  "0287": ["Kebumen", "Karanganyar", "Gombong", "Tambak"],
  "0289": ["Bumiayu", "Paguyangan (Brebes bagian selatan)"],
  "0291": ["Demak kecuali Mranggen, Sayung", "Jepara", "Kudus"],
  "0292": ["Grobogan", "Purwodadi"],
  "0293": ["Magelang", "Mungkid", "Temanggung"],
  "0294": ["Kendal", "Kaliwungu", "Weleri", "Batang bagian timur"],
  "0295": ["Pati", "Rembang", "Lasem"],
  "0296": ["Blora", "Cepu"],
  "0297": ["Karimun Jawa"],
  "0298": ["Salatiga", "Ambarawa (Kabupaten Semarang)"],
  "0299": ["Nusakambangan"],
  "031": ["Surabaya", "Gresik", "Sidoarjo", "Bangkalan"],
  "0321": ["Mojokerto", "Jombang"],
  "0322": ["Lamongan", "Babat"],
  "0323": ["Sampang"],
  "0324": ["Pamekasan"],
  "0325": ["Sangkapura (Bawean)"],
  "0327": ["Kepulauan Kangean", "Kepulauan Masalembu"],
  "0328": ["Sumenep"],
  "0331": ["Jember (kecuali Ambulu dan Puger)"],
  "0332": ["Bondowoso", "Sukosari", "Prajekan"],
  "0333": ["Banyuwangi", "Genteng", "Muncar"],
  "0334": ["Lumajang"],
  "0335": ["Probolinggo", "Kraksaan"],
  "0336": ["Ambulu", "Puger (Jember selatan)"],
  "0338": ["Situbondo", "Besuki"],
  "0341": ["Malang", "Kepanjen", "Batu"],
  "0342": ["Blitar", "Wlingi"],
  "0343": ["Pasuruan", "Pandaan", "Gempol"],
  "0351": ["Madiun", "Caruban", "Magetan", "Ngawi"],
  "0352": ["Ponorogo"],
  "0353": ["Bojonegoro"],
  "0354": ["Kediri", "Pare"],
  "0355": ["Tulungagung", "Trenggalek"],
  "0356": ["Tuban", "Rembang bagian Timur (berbatasan Tuban)"],
  "0357": ["Pacitan"],
  "0358": ["Nganjuk", "Kertosono"],
  "0361": [
    "Denpasar",
    "Gianyar",
    "Badung",
    "Tabanan (kecuali Baturiti)",
    "Tampaksiring",
    "Ubud (Gianyar)",
    "Nusa Dua",
    "Kuta (Badung)",
    "Sanur (Denpasar Selatan)",
  ],
  "0362": ["Singaraja (Buleleng)"],
  "0363": ["Amlapura (Karangasem)"],
  "0365": ["Negara", "Gilimanuk (Jembrana)"],
  "0366": ["Klungkung", "Bangli"],
  "0368": ["Baturiti (Tabanan)"],
  "0370": ["Mataram", "Praya"],
  "0371": ["Sumbawa"],
  "0372": ["Alas", "Taliwang"],
  "0373": ["Dompu"],
  "0374": ["Bima"],
  "0376": ["Selong"],
  "0380": ["Kupang", "Baa (Roti)"],
  "0381": ["Ende"],
  "0382": ["Maumere"],
  "0383": ["Larantuka"],
  "0384": ["Bajawa"],
  "0385": ["Labuhanbajo", "Ruteng"],
  "0386": ["Kalabahi"],
  "0387": ["Waingapu", "Waikabubak"],
  "0388": ["Kefamenanu", "Soe"],
  "0389": ["Atambua"],

  // Aceh
  "0627": ["Kota Subulussalam"],
  "0629": ["Kutacane (Kabupaten Aceh Tenggara)"],
  "0641": ["Kota Langsa"],
  "0642": ["Blang Kejeren (Kabupaten Gayo Lues)"],
  "0643": ["Takengon (Kabupaten Aceh Tengah)"],
  "0644": ["Bireuen (Kabupaten Bireuen)"],
  "0645": ["Lhoksukon (Kabupaten Aceh Utara)", "Kota Lhoksumawe"],
  "0646": ["Idi (Kabupaten Aceh Timur)"],
  "0650": ["Sinabang (Kabupaten Simeulue)"],
  "0651": ["Kota Banda Aceh", "Jantho", "Lamno"],
  "0652": ["Kota Sabang"],
  "0653": ["Sigli (Kabupaten Pidie)"],
  "0654": ["Calang (Kabupaten Aceh Jaya)"],
  "0655": ["Meulaboh (Kabupaten Aceh Barat)"],
  "0656": ["Tapaktuan (Kabupaten Aceh Selatan)"],
  "0657": ["Bakongan (Kabupaten Aceh Selatan)"],
  "0658": ["Singkil (Kabupaten Aceh Singkil)"],
  "0659": ["Blangpidie (Kabupaten Aceh Barat Daya)"],

  // Sumatera Utara
  "061": [
    "Kota Medan",
    "Kota Binjai",
    "Stabat (Kabupaten Langkat)",
    "Lubuk Pakam (Kabupaten Deli Serdang)",
    "Perbaungan - Pantai Cermin (Kabupaten Serdang Bedagai)",
  ],
  "0620": ["Pangkalan Brandan (Kabupaten Langkat)"],
  "0621": ["Kota Tebing Tinggi", "Sei Rampah (Kabupaten Serdang Bedagai)"],
  "0622": [
    "Kota Pematangsiantar",
    "Pematang Raya (Kabupaten Simalungun)",
    "Limapuluh (Kabupaten Batu Bara)",
  ],
  "0623": ["Kisaran (Kabupaten Asahan)", "Kota Tanjung Balai"],
  "0624": [
    "Rantau Prapat (Kabupaten Labuhanbatu)",
    "Aek Kanopan (Kabupaten Labuhanbatu Utara)",
    "Kota Pinang (Kabupaten Labuhanbatu Selatan)",
    "Panipahan (Kabupaten Rokan Hilir)",
  ],
  "0625": [
    "Parapat (Kabupaten Simalungun)",
    "Ajibata (Kabupaten Toba Samosir)",
    "Simanindo (Kabupaten Samosir)",
  ],
  "0626": ["Pangururan (Kabupaten Samosir)"],
  // "0627": ["Sidikalang (Kabupaten Dairi)", "Salak (Kabupaten Pakpak Bharat)"], // Duplicate with Aceh
  "0628": ["Kabanjahe (Kabupaten Karo)", "Sibolangit (Kabupaten Deli Serdang)"],
  "0630": ["Teluk Dalam (Kabupaten Nias Selatan)"],
  "0631": ["Kota Sibolga", "Pandan (Kabupaten Tapanuli Tengah)"],
  "0632": ["Balige (Kabupaten Toba Samosir)"],
  "0633": [
    "Tarutung (Kabupaten Tapanuli Utara)",
    "Dolok Sanggul (Kabupaten Humbang Hasundutan)",
  ],
  "0634": ["Kota Padang Sidempuan", "Sipirok (Kabupaten Tapanuli Selatan)"],
  "0635": ["Gunung Tua (Kabupaten Padang Lawas Utara)"],
  "0636": [
    "Panyabungan (Kabupaten Mandailing Natal)",
    "Sibuhuan (Kabupaten Padang Lawas)",
  ],
  "0639": ["Kota Gunung Sitoli"],

  // Sumatera Barat
  "0751": ["Kota Padang", "Kota Pariaman", "Kabupaten Padang Pariaman"],
  "0752": [
    "Kota Bukittinggi",
    "Kota Padang Panjang",
    "Kota Payakumbuh",
    "Kabupaten Tanah Datar",
    "Kabupaten Agam",
  ],
  "0753": ["Kabupaten Pasaman", "Kabupaten Pasaman Barat"],
  "0754": ["Kota Sawahlunto", "Kabupaten Sijunjung", "Kabupaten Dharmasraya"],
  "0755": [
    "Kota Solok",
    "Kabupaten Solok Selatan",
    "Arosuka (Kabupaten Solok)",
  ],
  "0756": ["Painan (Kabupaten Pesisir Selatan)"],
  "0757": ["Renah Indojati"],
  "0759": ["Kabupaten Kepulauan Mentawai"],

  // Riau
  "0760": ["Teluk Kuantan (Kabupaten Kuantan Singingi)"],
  "0761": [
    "Kota Pekanbaru",
    "Pangkalan Kerinci (Kabupaten Pelalawan)",
    "Minas - Tualang (Kabupaten Siak)",
  ],
  "0762": [
    "Bangkinang (Kabupaten Kampar)",
    "Pasir Pengaraian (Kabupaten Rokan Hulu)",
  ],
  "0763": ["Selatpanjang (Kabupaten Kepulauan Meranti)"],
  "0764": ["Siak Sri Indrapura (Kabupaten Siak)"],
  "0765": [
    "Kota Dumai",
    "Duri (Kabupaten Bengkalis)",
    "Bagan Batu (Kabupaten Rokan Hilir)",
    "Ujung Tanjung (Kabupaten Rokan Hilir)",
  ],
  "0766": ["Bengkalis (Kabupaten Bengkalis)"],
  "0767": ["Bagansiapiapi (Kabupaten Rokan Hilir)"],
  "0768": ["Tembilahan (Kabupaten Indragiri Hilir)"],
  "0769": ["Rengat - Air Molek (Kabupaten Indragiri Hulu)"],

  // Kepulauan Riau
  "0770": ["Batam Industrial Zone (Mukakuning)"],
  "0771": ["Kota Tanjungpinang dan Kabupaten Bintan"],
  "0772": ["Tarempa (Kabupaten Kepulauan Anambas)"],
  "0773": ["Ranai (Kabupaten Natuna)"],
  "0776": ["Dabosingkep (Kabupaten Lingga)"],
  "0777": ["Tanjung Balai Karimun (Kabupaten Karimun)"],
  "0778": ["Kota Batam"],
  "0779": ["Tanjungbatu (Kabupaten Karimun)"],

  // Jambi
  "0740": ["Mendahara - Muara Sabak (Kabupaten Tanjung Jabung Timur)"],
  "0741": ["Kota Jambi"],
  "0742": ["Kualatungkal (Kabupaten Tanjung Jabung Barat) - Tebingtinggijambi"],
  "0743": ["Muara Bulian (Kabupaten Batanghari)"],
  "0744": ["Muara Tebo (Kabupaten Tebo)"],
  "0745": ["Sarolangun (Kabupaten Sarolangun)"],
  "0746": ["Bangko (Kabupaten Merangin)"],
  "0747": ["Muarabungo (Kabupaten Bungo)"],
  "0748": ["Kota Sungai Penuh dan Kabupaten Kerinci"],

  // Sumatera Selatan
  "0702": ["Tebing Tinggi (Kabupaten Empat Lawang)"],
  "0711": [
    "Kota Palembang",
    "Pangkalan Balai - Betung (Kabupaten Banyuasin)",
    "Indralaya (Kabupaten Ogan Ilir)",
  ],
  "0712": [
    "Kayu Agung (Kabupaten Ogan Komering Ilir)",
    "Tanjung Raja (Kabupaten Ogan Ilir)",
  ],
  "0713": ["Kota Prabumulih", "Pendopo Talang Ubi (Kabupaten Muara Enim)"],
  "0714": ["Sekayu (Kabupaten Musi Banyuasin)"],
  "0730": ["Kota Pagar Alam", "Kota Agung (Kabupaten Lahat)"],
  "0731": ["Lahat (Kabupaten Lahat)"],
  "0733": ["Kota Lubuklinggau", "Muara Beliti (Kabupaten Musi Rawas)"],
  "0734": ["Muara Enim (Kabupaten Muara Enim)"],
  "0735": [
    "Baturaja (Kabupaten Ogan Komering Ulu)",
    "Martapura (Kabupaten Ogan Komering Ulu Timur)",
    "Muaradua (Kabupaten Ogan Komering Ulu Selatan)",
  ],

  // Kepulauan Bangka Belitung
  "0715": ["Belinyu (Kabupaten Bangka)"],
  "0716": ["Muntok (Kabupaten Bangka Barat)"],
  "0717": ["Kota Pangkal Pinang", "Sungailiat (Kabupaten Bangka)"],
  "0718": [
    "Koba (Kabupaten Bangka Tengah)",
    "Toboali (Kabupaten Bangka Selatan)",
  ],
  "0719": [
    "Manggar (Kabupaten Belitung Timur)",
    "Tanjung Pandan (Kabupaten Belitung)",
  ],

  // Bengkulu
  "0732": ["Curup (Kabupaten Rejang Lebong)"],
  "0736": ["Kota Bengkulu", "Lais (Kabupaten Bengkulu Utara)"],
  "0737": [
    "Arga Makmur (Kabupaten Bengkulu Utara)",
    "Mukomuko (Kabupaten Mukomuko)",
  ],
  "0738": ["Muara Aman (Kabupaten Lebong)"],
  "0739": [
    "Bintuhan (Kabupaten Kaur)",
    "Kota Manna (Kabupaten Bengkulu Selatan)",
  ],

  // Lampung
  "0721": [
    "Kota Bandar Lampung",
    "Gedong Tataan - Tegineneng (Kabupaten Pesawaran)",
    "Natar - Jati Agung (Kabupaten Lampung Selatan)",
  ],
  "0722": ["Kota Agung (Kabupaten Tanggamus)"],
  "0723": ["Blambangan Umpu (Kabupaten Way Kanan)"],
  "0724": ["Kotabumi (Kabupaten Lampung Utara)"],
  "0725": [
    "Kota Metro",
    "Gunung Sugih (Kabupaten Lampung Tengah)",
    "Sukadana (Kabupaten Lampung Timur)",
  ],
  "0726": [
    "Menggala (Kabupaten Tulang Bawang)",
    "Kabupaten Tulang Bawang Barat",
    "Wiralaga Mulya (Kabupaten Mesuji)",
  ],
  "0727": [
    "Kalianda (Kabupaten Lampung Selatan)",
    "Punduh Pidada (Kabupaten Pesawaran)",
  ],
  "0728": [
    "Kota Liwa (Kabupaten Lampung Barat)",
    "Krui (Kabupaten Pesisir Barat)",
  ],
  "0729": ["Pringsewu (Kabupaten Pringsewu)"],

  // Kalimantan Barat
  "0561": ["Pontianak", "Mempawah"],
  "0562": ["Sambas", "Singkawang", "Bengkayang"],
  "0563": ["Ngabang"],
  "0564": ["Sanggau"],
  "0565": ["Sintang"],
  "0567": ["Putussibau"],
  "0568": ["Nanga Pinoh"],
  "0534": ["Ketapang"],

  // Kalimantan Tengah
  "0513": ["Muara Teweh"],
  "0522": ["Ampah (Dusun Tengah, Barito Timur)"],
  "0525": ["Buntok"],
  // "0526": ["Tamiang Layang"], // Duplicate with other regions
  "0528": ["Purukcahu"],
  "0531": ["Sampit"],
  "0532": ["Pangkalan Bun", "Kumai"],
  "0536": ["Palangkaraya", "Kasongan"],
  "0537": ["Kuala Kurun"],
  "0538": ["Kuala Pembuang"],
  "0539": ["Kuala Kuayan (Mentaya Hulu, Kotawaringin Timur)"],

  // Kalimantan Selatan
  "0511": ["Banjarmasin", "Banjarbaru", "Martapura", "Marabahan"],
  "0512": ["Pelaihari"],
  "0517": ["Kandangan", "Barabai", "Rantau", "Negara"],
  "0518": ["Kotabaru", "Batulicin"],
  // "0526": ["Tanjung", "Balangan"], // Duplicate
  "0527": ["Amuntai"],

  // Kalimantan Timur
  "0541": ["Samarinda", "Tenggarong"],
  "0542": ["Balikpapan"],
  "0543": ["Tanah Grogot"],
  "0545": ["Melak"],
  "0548": ["Bontang"],
  "0549": ["Sangatta"],
  "0554": ["Tanjung Redeb (Berau)"],

  // Kalimantan Utara
  "0551": ["Tarakan", "Bunyu"],
  "0552": ["Tanjungselor", "Tana Tidung"],
  "0553": ["Malinau"],
  "0556": ["Nunukan"],

  // Sulawesi Utara
  "0430": ["Amurang (Kabupaten Minahasa Selatan)"],
  "0431": ["Manado", "Tomohon", "Tondano"],
  "0432": ["Tahuna (Kabupaten Kepulauan Sangihe)"],
  "0434": ["Kotamobagu"],
  "0438": ["Bitung"],

  // Gorontalo
  "0435": ["Gorontalo", "Limboto"],
  "0443": ["Marisa"],

  // Sulawesi Tengah
  "0445": ["Buol"],
  "0450": ["Parigi"],
  "0451": ["Palu"],
  "0452": ["Poso"],
  "0453": ["Tolitoli"],
  "0454": ["Tinombo"],
  "0455": ["Kota Raya", "Moutong"],
  "0457": ["Donggala"],
  "0458": ["Tentena"],
  "0461": ["Luwuk"],
  "0462": ["Banggai"],
  "0463": ["Bunta"],
  "0464": ["Ampana"],
  "0465": ["Kolonedale"],

  // Sulawesi Barat
  "0422": ["Majene"],
  "0426": ["Mamuju"],
  "0428": ["Polewali"],

  // Sulawesi Selatan
  "0410": ["Pangkep"],
  "0411": ["Makassar", "Maros", "Sungguminasa"],
  "0413": ["Bulukumba", "Bantaeng"],
  "0414": ["Kepulauan Selayar"],
  "0417": ["Malino"],
  "0418": ["Takalar"],
  "0419": ["Jeneponto"],
  "0420": ["Enrekang"],
  "0421": ["Parepare", "Pinrang"],
  "0423": ["Makale", "Rantepao"],
  "0427": ["Barru"],
  "0471": ["Palopo"],
  "0472": ["Pitumpanua"],
  "0473": ["Masamba"],
  "0474": ["Malili"],
  "0475": ["Soroako"],
  "0481": ["Watampone"],
  "0482": ["Sinjai"],
  "0484": ["Watansoppeng"],
  "0485": ["Sengkang"],

  // Sulawesi Tenggara
  "0401": ["Kendari"],
  "0402": ["Baubau"],
  "0403": ["Raha"],
  "0404": ["Wanci"],
  "0405": ["Kolaka"],
  "0408": ["Kota Unaaha"],

  // Maluku
  "0910": ["Bandanaira"],
  "0911": ["Ambon"],
  "0913": ["Namlea"],
  "0914": ["Masohi"],
  "0915": ["Bula"],
  "0916": ["Tual"],
  "0917": ["Dobo"],
  "0918": ["Saumlaku"],
  "0921": ["Soasiu", "Sofifi"],
  "0922": ["Jailolo"],
  "0923": ["Morotai"],
  "0924": ["Tobelo"],
  "0927": ["Labuha"],
  "0929": ["Sanana"],
  "0931": ["Saparua"],

  // Papua
  "0901": ["Timika", "Tembagapura"],
  "0902": ["Agats (Asmat)"],
  "0951": ["Sorong"],
  "0952": ["Teminabuan"],
  "0955": ["Bintuni"],
  "0956": ["Fakfak"],
  "0957": ["Kaimana"],
  "0966": ["Sarmi"],
  "0967": ["Jayapura", "Abepura"],
  "0969": ["Wamena"],
  "0971": ["Merauke"],
  "0975": ["Tanahmerah"],
  "0980": ["Ransiki"],
  "0981": ["Biak"],
  "0983": ["Serui"],
  "0984": ["Nabire"],
  "0985": ["Nabire"],
  "0986": ["Manokwari"],
};
